#============================================================================
#
# simple project makefile
#
# (c) Wouter van Ooijen (wouter@voti.nl) 2017
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at 
# http://www.boost.org/LICENSE_1_0.txt) 
#
#============================================================================

# source files in this project (main.* is automatically assumed)
SOURCES += hwlib-adc.cpp
SOURCES += hwlib-common.cpp
SOURCES += hwlib-console.cpp
SOURCES += hwlib-dac.cpp
SOURCES += hwlib-defines.cpp
SOURCES += hwlib-demo.cpp
SOURCES += hwlib-font-default-8x8.cpp
SOURCES += hwlib-font-default-16x16.cpp
SOURCES += hwlib-glcd-5510.cpp
SOURCES += hwlib-glcd-oled.cpp
SOURCES += hwlib-graphics.cpp
SOURCES += hwlib-hc595.cpp
SOURCES += hwlib-hd44780.cpp
SOURCES += hwlib-i2c.cpp
SOURCES += hwlib-ostream.cpp
SOURCES += hwlib-panic.cpp
SOURCES += hwlib-pcf8574a.cpp
SOURCES += hwlib-pcf8591.cpp
SOURCES += hwlib-pin.cpp
SOURCES += hwlib-pin-decorators.cpp
SOURCES += hwlib-pin-dummies.cpp
SOURCES += hwlib-port.cpp
SOURCES += hwlib-port-decorators.cpp
SOURCES += hwlib-port-from-pins.cpp
SOURCES += hwlib-spi.cpp
SOURCES += hwlib-string.cpp
SOURCES += hwlib-wait.cpp


# header files in this project
HEADERS :=

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/makefile.link