#############################################################################
#
# makefile.link
#
# common settings for a native project
#
# (c) Wouter van Ooijen (www.voti.nl) 2017
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at 
# http://www.boost.org/LICENSE_1_0.txt)
# 
#############################################################################

# common settings for native 
TARGET            ?= native

# enable exeptions (disabled by default by bmptk)
PROJECT_CPP_FLAGS += -fexceptions

# defer to the next-level makefile
RELATIVE          ?= .
RELATIVE          := $(RELATIVE)/..
include           $(RELATIVE)/makefile.link
