#############################################################################
#
# makefile.link
#
# common settings and uplink for ARduino Due projects
#
# (c) Wouter van Ooijen (wouter@voti.nl) 2017
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at 
# http://www.boost.org/LICENSE_1_0.txt)
# 
#############################################################################

# common settings for Arduino Uno projects
TARGET            ?= my_first_dev_board
SERIAL_PORT       ?= COM4
CONSOLE_BAUDRATE  ?= 2400

# defer to the next-level makefile
RELATIVE          ?= .
RELATIVE          := $(RELATIVE)/..
include           $(RELATIVE)/makefile.link
